/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utadeo.tamagochi.views;

import com.utadeo.tamagochi.views.Nombrem;

/**
 *
 * @author LENOVO
 */
public class Mascota extends javax.swing.JFrame {

    /**
     * Creates new form Mascota
     */
    public Mascota() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BPANDA = new javax.swing.JButton();
        BPINGUINO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELIGE A TU MASCOTA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BPANDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BPANDA.PNG"))); // NOI18N
        BPANDA.setText("BPANDA");
        BPANDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPANDAActionPerformed(evt);
            }
        });
        jPanel1.add(BPANDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 220, 100));

        BPINGUINO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BPINGUIDO.PNG"))); // NOI18N
        BPINGUINO.setText("BPINGUINO");
        BPINGUINO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPINGUINOActionPerformed(evt);
            }
        });
        jPanel1.add(BPINGUINO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 220, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FE_MASCOTA.PNG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPANDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPANDAActionPerformed
        Nombrem newframe = new Nombrem();
        newframe.setTipo("PA");
        newframe.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_BPANDAActionPerformed

    private void BPINGUINOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPINGUINOActionPerformed
        Nombrem newframe = new Nombrem();
        newframe.setTipo("PI");
        newframe.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_BPINGUINOActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPANDA;
    private javax.swing.JButton BPINGUINO;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
