/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utadeo.tamagochi.views;



/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BJUGAR = new javax.swing.JButton();
        BREGLAS = new javax.swing.JButton();
        BSONIDO = new javax.swing.JButton();
        BSALIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAMAGOCHI");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BJUGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BJUGAR.PNG"))); // NOI18N
        BJUGAR.setText("BJUGAR");
        BJUGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJUGARActionPerformed(evt);
            }
        });
        jPanel1.add(BJUGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 160, 70));

        BREGLAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BREGLAS.PNG"))); // NOI18N
        BREGLAS.setText("BREGLAS");
        BREGLAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BREGLASActionPerformed(evt);
            }
        });
        jPanel1.add(BREGLAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, 70));

        BSONIDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BSONIDO.PNG"))); // NOI18N
        BSONIDO.setText("BSONIDO");
        BSONIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSONIDOActionPerformed(evt);
            }
        });
        jPanel1.add(BSONIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 160, 70));

        BSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BSALIR.PNG"))); // NOI18N
        BSALIR.setText("BSALIR");
        BSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(BSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FMENUIMA.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -2, 650, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BJUGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJUGARActionPerformed
        Mascota newframe = new Mascota();
        newframe.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_BJUGARActionPerformed

    private void BSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BSALIRActionPerformed

    private void BREGLASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BREGLASActionPerformed
        Reglas newframe = new Reglas();
        newframe.setVisible(true);
       
        this.dispose();
        
    }//GEN-LAST:event_BREGLASActionPerformed

    private void BSONIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSONIDOActionPerformed
        Sonido newframe = new Sonido();
        newframe.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_BSONIDOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BJUGAR;
    private javax.swing.JButton BREGLAS;
    private javax.swing.JButton BSALIR;
    private javax.swing.JButton BSONIDO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
