/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utadeo.tamagochi.views;
import com.utadeo.tamagochi.database.daos.TamagochiDAO;
import com.utadeo.tamagochi.database.entities.Tamagochi;
import java.applet.AudioClip;
import java.util.List;

/**
 *
 * @author LENOVO
 */
public class Sonido extends javax.swing.JFrame {

    /**
     * Creates new form Sonido
     */
    public Sonido() {
        initComponents();
        iniciarSonido();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BSALIDAS = new javax.swing.JButton();
        sonidoJLabel = new javax.swing.JLabel();
        muteJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SONIDO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSALIDAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/X.PNG"))); // NOI18N
        BSALIDAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSALIDASActionPerformed(evt);
            }
        });
        jPanel1.add(BSALIDAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 80, 50));

        sonidoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sonido.png"))); // NOI18N
        sonidoJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sonidoJLabelMouseClicked(evt);
            }
        });
        jPanel1.add(sonidoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, 140));

        muteJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mute.png"))); // NOI18N
        muteJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muteJLabelMouseClicked(evt);
            }
        });
        jPanel1.add(muteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FMenu.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 668));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void iniciarSonido(){
        AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/sounds/Sonidow.wav"));
        //sounds/Sonido.mp3
        sonido.play();
       
    }
    private void BSALIDASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSALIDASActionPerformed
        Menu newframe = new Menu();
        newframe.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_BSALIDASActionPerformed

    private void sonidoJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonidoJLabelMouseClicked
        TamagochiDAO tamagochiDAO = new TamagochiDAO();
        List<Tamagochi> tamagochis = tamagochiDAO.getAll();
        if (tamagochis.size()>0){
            Tamagochi tamagochi = tamagochis.get(0);
            tamagochi.setMusica(true);
            tamagochiDAO.update(tamagochi);
        }
    }//GEN-LAST:event_sonidoJLabelMouseClicked

    private void muteJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muteJLabelMouseClicked
        TamagochiDAO tamagochiDAO = new TamagochiDAO();
        List<Tamagochi> tamagochis = tamagochiDAO.getAll();
        if (tamagochis.size()>0){
            Tamagochi tamagochi = tamagochis.get(0);
            tamagochi.setMusica(false);
            tamagochiDAO.update(tamagochi);
        }
    }//GEN-LAST:event_muteJLabelMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSALIDAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel muteJLabel;
    private javax.swing.JLabel sonidoJLabel;
    // End of variables declaration//GEN-END:variables
}
